ARG PYTHON_VERSION=3.14
FROM python:${PYTHON_VERSION}-slim

RUN apt-get update && \
    apt-get install -y build-essential gcc
    
WORKDIR /app
COPY . .
RUN python -m pip install --upgrade pip tox

CMD bash -lc 'ENV=py$(python -c "import sys;print(f\"{sys.version_info.major}{sys.version_info.minor}\")"); tox -e $ENV'

